### ISSUE TITLE
How to generate a completion

### ISSUE THREAD

**Issue by menithya** [jlewi/foyle#109]
Hi 
Followed  below document, downloaded  
`foyle_0.0.9_darwin_amd64`

https://foyle.io/docs/getting-started/

I am able to run the server. However, I am getting no suggestion when I type below commands.

![image](https://github.com/jlewi/foyle/assets/1724194/af7abdc7-f565-40c1-b4e5-26659ab3f000)

![image](https://github.com/jlewi/foyle/assets/1724194/4fe7e56f-d4ed-4963-bb4c-beb57c05357c)

![image](https://github.com/jlewi/foyle/assets/1724194/bae286ed-fbf8-4028-b192-b3d59ffaf793)

it is good to update prerequisite document for the installation.

**Comment by jlewi** [comment]
How did you try to generate a suggestion? 

To generate a suggestion you need to invoke command "Foyle Generate a completion" you can do this by 
* Open the command pallet and search for Foyle generate a completion
* Use the shortcut key:
   “win;” - on windows
   “cmd;” - on mac

Based on your screen shot it looks like you entered natural language - "fetch the hdro logs for the images" in a code cell and then tried to execute a code cell. So the exitCode - "-1" indicates an error because its not a valid command.

So what you probably meant to do is 

1. Create a markdown cell and enter the text "Fetch the hydros logs for the images"
2. Generate a completion by running the command "Foyle Generate a completion"

**Comment by menithya** [comment]
Thank you, I followed your suggesion

Step 1: select Foyle generate a completion

![image](https://github.com/jlewi/foyle/assets/1724194/5433be70-4793-48f4-8c36-9ba5852bc7ee)

Setp2: Fetch the hydros logs for the images"

<img width="612" alt="image" src="https://github.com/jlewi/foyle/assets/1724194/6366f624-ad8d-4d3a-8531-e5b1f05d5ade">

**Comment by jlewi** [comment]
Sorry your having trouble. To help troubleshoot this can you 

1. Open the developer tools console in your webbrowser
2. Issue a generate command
3. Collect any logs in the developer console

Upload the json logs from foyle. 

1. After you attempt to generate a request
2. Shutdown the Foyle server
3. Upload the JSON logs in ~/.foyle/raw

The screenshot you provided earlier doesn't show a generate request being sent. So I'd like to look at the logs in the case where you do generate a completion to see if a generate request actually gets sent. That will help us narrow down the problem.

**Comment by menithya** [comment]
Chrome browser logs
[localhost-1715951210360_foyle.log](https://github.com/jlewi/foyle/files/15349606/localhost-1715951210360_foyle.log)

Foyle logs:
I did not find ~/foyle/raw

![image](https://github.com/jlewi/foyle/assets/1724194/048fb68d-6fbb-4a1e-9c97-35553fdeb2cd)

![image](https://github.com/jlewi/foyle/assets/1724194/d41622eb-35b0-45a4-90d1-a8f32e2e6ce8)

**Comment by menithya** [comment]
Looks like installation problem for me. After rectifying same issue exist.
To install I did this.

```
# Make the file executable
chmod +x foyle_0.0.9_darwin_arm64

# Move the file to /usr/local/bin
sudo mv foyle_0.0.9_darwin_arm64 /usr/local/bin/foyle

# Run the program
foyle
```


[foyle_chrom_console.log](https://github.com/jlewi/foyle/files/15359728/foyle_chrom_console.log)
logs
[foyle.logs.2024-05-18T09:15:46.json](https://github.com/jlewi/foyle/files/15359741/foyle.logs.2024-05-18T09.15.46.json)

**Comment by jlewi** [comment]
I didn't quite understand your last message.  What's the connection between installation and the issue you are having?

For some reason a generate request isn't being sent and its not clear why. There's two things we can do here

1. We can hop on a call to try to debug this together ; shoot me an email at jeremy@lewi.us and we can arrange for a time
2. Wait for a future release with additional instrumentation to try to debug
