### ISSUE TITLE
Ghost Rendering For Markdown cells

### ISSUE THREAD

**Issue by jlewi** [jlewi/foyle#168]
Follow on to #167 

It looks like currently the cell decorations that we apply to render cells as ghost cells doesn't work for markdown cells. I think this maybe because when markdown cells are inserted; they are inserted in rendered mode not edit mode. If we were to put them in edit mode maybe the cell decorations would apply.

I think we are hitting some limitations with VSCode Notebook API

* MD cells can't be inserted in edit mode 
* You can put cells into mode but I think you may have to put the focus on them; Claude says

```
vscode.commands.executeCommand('notebook.cell.edit');
```

* I think this puts the focus on the new cell which we may not want to do

Do we want the AI to generate markdown cells?

* If the current focus is on a markdown cell then it makes sense that the AI should be strongly biased towards generating a code cell (at least as its first completion)

* However if the current cell is a code cell; possibly one that's just been executed then we might want to generate a markdown cell
  * For example, we'd like the AI to reason about the output

* For Markdown we could potentially use HTML & CSS to do the styling

**Comment by jlewi** [comment]
The vscode repository pointed me at StackOverflow so I posted a question there
https://stackoverflow.com/questions/78823333/how-to-programmatically-insert-vscode-notebook-cells-in-edit-mode

I found a function [updataEditState](https://github.com/microsoft/vscode/blob/d00533a1df0778ab3a3fe8200b18cd59e3d1b722/src/vs/workbench/contrib/notebook/browser/viewModel/baseCellViewModel.ts#L621) but I don't think that is part of the public API.

**Comment by sourishkrout** [comment]
I wonder if https://code.visualstudio.com/api/extension-guides/markdown-extension could be leveraged to replicate the grayed-out ghost presentation. I haven't played around with it much yet, and it's unclear how much contextual awareness the individual cells have. However, it wouldn't be the first time working around the APIs inside of the Extension Platform.

**Comment by jlewi** [comment]
Another workaround would be to turn the markdown into a comment included in the code cell.
This isn't an ideal solution but would provide some visual affordance while not forcing us to completely drop the AIs "thinking"

**Comment by jlewi** [comment]
The frontend change is in https://github.com/stateful/vscode-runme/releases/tag/3.9.0
