### ISSUE TITLE
Trigger Foyle Ghost Cell Updates When Cell Output Changes / Cell Is Executed

### ISSUE THREAD

**Issue by jlewi** [jlewi/foyle#309]
Now that we can render markup cells as Ghost Cells #1713 we'd like to trigger Ghost Cell Updates when the output of a code cell changes. We'd like the AI to reason about the output and figure out what to do next.

Right now we trigger completion generation in response to onDidChangeTextDocument
https://github.com/stateful/vscode-runme/blob/90fcc5b60322b4fe34be714ac120a5794004f837/src/extension/ai/manager.ts#L57

That doesn't appear to trigger in the event a user executes a cell or in response to cell output change. I assume this is because the cell outputs aren't textDocuments.

Our handler is filtering by scheme `vscode-notebook-cell` here https://github.com/stateful/vscode-runme/blob/90fcc5b60322b4fe34be714ac120a5794004f837/src/extension/ai/ghost.ts#L308C40-L308C60 
but I added some logging and it doesn't look like that is causing update events to output cells to be dropped.

I couldn't find a VSCode API that automatically does this. 

Runme is refreshing cell outputs. We could intercept that and trigger suggestion generation.

Is [refreshOutput](https://github.com/stateful/vscode-runme/blob/90fcc5b60322b4fe34be714ac120a5794004f837/src/extension/cell.ts#L396) the right place to try to intercept this?

Are there different code paths for interactive and non-interactive cells?

Related:
https://github.com/jlewi/foyle/issues/286#issuecomment-2406119116

**Comment by jlewi** [comment]
@sourishkrout  thoughts?

**Comment by jlewi** [comment]
Draft PR
https://github.com/stateful/vscode-runme/pull/1744/files

**Comment by jlewi** [comment]
That's not quite working. It looks like in some cases the output is missing when the event fires.

How are output cells represented? Are they TextDocuments? Is the reason onDidChangeActiveTextEditor and onDidChangeVisibleTextEditors isn't firing for output windows because they aren't text editors?

@sourishkrout do you know how they are represented?

**Comment by jlewi** [comment]
It looks like there is an event ` vscode.workspace.onDidChangeNotebookDocument` that fires in response to changes that includes adding output items.

**Comment by jlewi** [comment]
#1744 appears to have fixed this for non-interactive cells. I was hoping with #1756 it would fix the issue for interactive cells but that doesn't appear to be the case.

The problem with interactive cells can be demonstrated by using a long running command like the following.

```
for i in {1..180}; do
  echo "Interactive Iteration: $i - DateTime: $(date)"
  sleep 3
done
```

We'd like cell generation to be triggered each time the output updates. The problem is that `vscode.workspace.onDidChangeNotebookDocument` doesn't appear to fire for interactive cells on each iteration of the loop. This can be confirmed by adding a longing statement to our handler. It does fire for non-interactive cells.

I think this behavior is consistent with (#286). As with #286, for interactive cells the output items in an interactive cell are not immediately updated. Since the outputItem isn't immediately updated it makes sense that onDidChangeNotebookDocument wouldn't fire.

If I understand https://github.com/jlewi/foyle/issues/286#issuecomment-2414526556 interactive cells are actually rendering a web-component using xterm.js. That would explain why the output is visible to the user even though its not triggering an onDidChangeNotebookDocument event.

I think there are a couple of ways we could potentially solve that.

1. We could try to intercept the xterm.js changes trigger completions
2. We could presumably hook into Runme's kernel code and use that to trigger completions
    * Presumably there must be logic somewhere listening for responses from the Executor service
    * So we could presumably intercept that and use that to trigger completions

2 seems like a better idea.

A case could be made that "interactive + long running" is a bit of an edge case and maybe we don't need to support that. Currently, Foyle is forcing all generated cells to be non interactive.

The problem with using non-interactive cells is that non-interactive cells don't show stderr. https://github.com/jlewi/foyle/issues/286#issuecomment-2414499139

**Comment by sourishkrout** [comment]
> We'd like cell generation to be triggered each time the output updates. The problem is that `vscode.workspace.onDidChangeNotebookDocument` doesn't appear to fire for interactive cells on each iteration of the loop. This can be confirmed by adding a longing statement to our handler. It does fire for non-interactive cells.

This makes sense. I didn't realize at first that Foyle needed streaming updates.

There is indeed a way (using Runme APIs; VS Code makes this hard/impossible) to get streaming updates from the cell while it's executing. Non-interactive cells are different with the lack of tty-allocation. It offers no interactivity, so we basically update the document upon completion. I'm saying basically here because we do intermediate updates of the cell to account for partial renders. Heavy throttling is being used to avoid "flickering", UX issues, and overloading the CPU since the Notebook extension APIs are not built for frequent updates.

> I think there are a couple of ways we could potentially solve that.
> 
> 1. We could try to intercept the xterm.js changes trigger completions
> 2. We could presumably hook into Runme's kernel code and use that to trigger completions
>    
>    * Presumably there must be logic somewhere listening for responses from the Executor service
>    * So we could presumably intercept that and use that to trigger completions
> 
> 2 seems like a better idea.

Let me take a closer look at the code. The good news is that it's conceptually possible to get hold of the PTY/TTY's stream (stdout+stderr combined). However, I have to figure out how to be expose it as an API that can be consumed here. I imagine the solution to move the event reporting deeper down into the logic interfacing with the kernel.

Do you already separate out events as "executing" with a chunk of data versus "completion" when a cell execution ends?

**Comment by jlewi** [comment]
Appreciate the explanation @sourishkrout.

> Do you already separate out events as "executing" with a chunk of data versus "completion" when a cell execution ends?

No we don't.

Long running commands (e.g. the bash program I posted above) are a bit of an edge case so they may not be worth worrying about.

I think the most important case we want to cover is making sure we trigger a completion when cell execution is complete and we have the output available. Do you have suggestions on where we can hook in to trigger that?

Originally in #1744 I tried firing an event after _doExecute finished. Basically, we are already reporting the execution along with status via the eventReporter (https://github.com/stateful/vscode-runme/blob/314c6d3af5323f993057d5e8a1458f0a0f724494/src/extension/kernel.ts#L829), so I just modified the eventReporter to trigger completion generation
(https://github.com/stateful/vscode-runme/pull/1744/commits/38e589ff669074b97b93d4316261ad7f564bb35f#diff-f0a5c022488c3922874e791475fce22933ea551ffbc4a37c414de2831f8af593)

However, it seemed those events lacked the actual cell output which is why I started intercepting the vscode.workspace.onDidChangeNotebookDocument events. I suspect though maybe the reason the outputs were missing was because I wasn't calling addExecInfo. 

Do you think triggering completion after _doExecute is a better solution?

**Comment by sourishkrout** [comment]
> Do you think triggering completion after _doExecute is a better solution?

Effectively, `_doExecute` will be exactly the same as `_doExecuteCell`. They are just separated for code readability.

To recap, are you saying that you are still missing outputs? If so, I'd suggest moving down into the runner's path that populates the cells in the notebook. This would resemble how reporting worked inside the Kernel (golang). However, without the downside of decoupling it entirely from the UI/UX.

The truth is that VS Code's notebook APIs (especially events) are not fine-granular enough because they are a very opinionated yet "dumb" view layer.

**Comment by jlewi** [comment]
> To recap, are you saying that you are still missing outputs?
Correct. In the case of interactive cells we aren't triggering when the command completes. 

>  If so, I'd suggest moving down into the runner's path that populates the cells in the notebook. 
I think I understand and agree with that. 
Concretely, I'm thinking of piggy backing on the reportExecution call here
https://github.com/stateful/vscode-runme/blob/165da756be8ef14ee604c2b9afb352f26ca2841e/src/extension/kernel.ts#L829

IUC that fires when the cell has finished running. So if we trigger there we should be able to include the entire cell output.

I'll create a PR and shoot it your way.

**Comment by jlewi** [comment]
#1775 doesn't seem to work as desired with interactive terminals. It seems like we might be triggering but the output might be missing. I need to debug that further to see if that's whats happening.
