### ISSUE TITLE
Fix bluesky logo on homepage

### ISSUE THREAD

**Issue by jlewi** [jlewi/foyle#335]
#334 replaced the follow me on twitter section with bluesky.
It added a bluesky logo but its not showing up. I think because it uses the block quote feature in the hugo template and we need to figure out how to use it with a custom icon.

**Comment by IndySeh** [comment]
G’day Jeremy! Is there a particular reason for using a custom Bluesky logo instead of the Font Awesome **fab fa-bluesky icon**?

I’ve fixed this locally by switching to the Font Awesome icon. If this works for you, I can **submit a PR within the hour**.  Please Let me know mate, ta!

**Comment by jlewi** [comment]
@IndySeh That would be awesome. The only reason I wasn't using that icon was I didn't know it existed.

**Comment by IndySeh** [comment]
@jlewi Thanks mate! Done.
